### ISSUE TITLE
some text appears to have a hard-coded color

### ISSUE THREAD

**Issue by cgsdev0** [amonks/run#105]
particularly the text at the bottom, but also some of the file watcher messages too

it is very hard to read on my light theme:
![image](https://github.com/amonks/run/assets/4583705/c03adbbf-0121-48ce-858b-a4d955a1f2f7)

**Comment by amonks** [comment]
Ahhhh darn you’re totally right. 

I took a stab at fixing this class of issue in #103, but I think backgrounds went too far: they’d tear if you scrolled quickly. 

I think I should land a smaller version of #103 that normalizes colors everywhere but does not set any backgrounds.

**Comment by amonks** [comment]
ah! adaptive colors weren't working for me because I have my tmux configured to pretend not to be tmux (my $SHELL doesn't have prefix "tmux" or "screen").

That prevented termenv from reading my background color, so lipgloss always assumed dark background by default, and so text would be printed in light colors. So, when I tried to use run with a light background, it looked horrible.

In #103, I tried to correct this by specifying background colors everywhere, but, as you noted, that's a very heavy-handed change.

I modified #75 to using the system background color everywhere, and adds support for adaptive colors: if your terminal is dark, text will be bright, and vice versa.

In the future, It might be preferable to use your terminal's configured 'normal' and 'bright' colors, but I think I'm currently using at least 4 colors for text, and compressing that down to 2 would take some thought.
